version: '3.5'

services:
  app:
    image: lastalex/cinema_friday:1.0.0
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PG_HOST: pg
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_PORT: ${PG_PORT}
    ports:
      - 8000:8000
    links:
      - pg
    command: >
      sh -c "python manage.py migrate &&
            python manage.py upload_data_fb &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pg
  pg:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: