name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up P  ython ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: ${{ secrets.PG_DB_NAME }}
        postgresql user: ${{ secrets.PG_USER }}
        postgresql password: ${{ secrets.PG_PASSWORD }}
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        PG_USER: ${{ secrets.PG_USER }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        PG_DB_NAME:  ${{ secrets.PG_DB_NAME }}
        PG_HOST: ${{ secrets.PG_HOST }}
        PG_PORT: ${{ secrets.PG_PORT }}
      run: |
        cd cinemaFriday/
        python manage.py migrate
        python manage.py test
