name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: ${{ secrets.POSTGRES_DB }}
        postgresql user: ${{ secrets.POSTGRES_USER }}
        postgresql password: ${{ secrets.POSTGRES_PASSWORD }}
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB:  ${{ secrets.POSTGRES_DB }}
        PG_HOST: ${{ secrets.PG_HOST }}
        PG_PORT: ${{ secrets.PG_PORT }}
      run: |
        cd cinemaFriday/
        python manage.py migrate
        python manage.py test
